### ISSUE TITLE
Inference is case-sensitive

### ISSUE THREAD

**Issue by memoryfull** [abessudnov/ruEthnicNamesPublic#1]
Inference seems to be case-sensitive. Simply put, `Лидия Кузнецова` (Lidia Kuznetsova) will be 100% Russian whereas `ЛИДИЯ КУЗНЕЦОВА` will be 65% Moldovan. [Here](https://colab.research.google.com/drive/1GZQXQHzsT4eeyonySdEmgxHd9ai91aA5) is a Colab notebook to replicate this result.

Is this documented behaviour or data leakage? I believe this is an important limitation that should be spelled out since many datasets include case-insensitive (e.g. uppercased) names. Not knowing that input is case-sensitive could result in severe pro-Moldovan bias.

Or, better yet, have you considered retraining the classifier with augmented data where symbols/grams are randomly upper/lowercased to make the classifier truly case-insensitive?

**Comment by DT6A** [comment]
Thanks a lot for reporting an issue. I've just fixed this. Now classifiers are case insensitive. Please let us know if you still have problems with it.

**Comment by memoryfull** [comment]
Thank you, now it is case-insensitive, I just checked in Google Colab.
