### ISSUE TITLE
A few notes

### ISSUE THREAD

**Issue by cjerzak** [abessudnov/ruEthnicNamesPublic#2]
Great package! Appreciate your work on it. Small note: 

In the documentation for mlPipeline, I think 

"first_name and last_names columns" should read "first_name and last_name columns" 

Have been working on getting this working in an R environment -- happy to share a tutorial doing that if it'd be helpful, too.

**Comment by abessudnov** [comment]
Hi Connor, Many thanks for your interest and comment. I'd be very happy to add a link to your R tutorial!

**Comment by hillnf** [comment]
Hello, I appreciate the creation of this package. I was wondering if the link to the R Tutorial is available yet?

**Comment by cjerzak** [comment]
hey @hillnf 

thanks for this note; i haven't had a chance to make this tutorial yet. however, attached is the script we used in [our project](https://osf.io/preprints/osf/ums8y_v2) using this codebase. more soon. 

[InstRunRussianNames.txt](https://github.com/user-attachments/files/20030698/InstRunRussianNames.txt)

**Comment by hillnf** [comment]
Thank you @cjerzak much appreciated!
